### ISSUE TITLE
Drop Python2 compatibility

### ISSUE THREAD

**Issue by larsrinn** [hzdg/django-enumfields#100]
Django dropped Python2 support a while ago already. In Django 3.0 `python_2_unicode_compatibility` and `django.utils.six` have been deleted. Hence starting an application that uses `django-enumfields` fails.

**Comment by brianwawok** [comment]
Indeed. Very easy to make the fix.

I would be happy to put together a 1.0 release that only supports python3 (I have it done locally). Current users could feel free to use the 0.9 release. If I were to make a PR like this, would @talebbits or someone else be willing to merge me and push to pypi?

**Comment by johnthagen** [comment]
See #96, a fork may be needed to keep this project alive. 😕

**Comment by matthewwithanm** [comment]
@lettertwo @talebbits How about adding another maintainer?

**Comment by johnthagen** [comment]
Could also remove `enum34` usage when dropping Python 2.7:

https://github.com/hzdg/django-enumfields/blob/70a2f2cd76a05ac528c35fd099ea5cf595fa0e61/setup.py#L65
