### ISSUE TITLE
Add Django 1.7 to tests

### ISSUE THREAD

**Issue by matthewwithanm** [hzdg/django-enumfields#20]
Currently, [we're only testing up to 1.6][1].

[1]: https://github.com/hzdg/django-enumfields/blob/4a904f18feb7e75d9dbb24610170a162df634577/tox.ini

**Comment by akx** [comment]
I think f911c6d03b32e1cc36c714eb55c0e204ecaff61b closed this :)

**Comment by matthewwithanm** [comment]
:thumbsup: Yup, thanks!
