### ISSUE TITLE
Allow enums with multiple variables.

### ISSUE THREAD

**Issue by AncientSwordRage** [hzdg/django-enumfields#27]
I've created an enum with an `__init__` method, which should be [fine](https://docs.python.org/3/library/enum.html#planet). But it looks like django is confused when it tries to store that in the database.

My Enum/class is as below:

    class SkillAbility(models.Model):

        class Skills(Enum):
            ACADEMICS = ('Academics', 'Mental')
            COMPUTER = ('Computer', 'Mental')
        def __init__(self, label, skill_type):
            self.label = label
            self.skill_type = skill_type

        @property
        def type(self):
            return self.skill_type
    skill = EnumField(Skills)

And this is the error code from Django:

    InterfaceError at /admin/characters/skillability/add/
    Error binding parameter 0 - probably unsupported type.

This is the method:

    def execute(self, query, params=None):
            if params is None:
                return Database.Cursor.execute(self, query)
            query = self.convert_query(query)
            return Database.Cursor.execute(self, query, params) 

And these are the values of the local variables:

    params: [('Academics', 'Mental')]
    query: 'INSERT INTO "characters_skillability" ("skill") VALUES (?)'
    self: <django.db.backends.sqlite3.base.SQLiteCursorWrapper object at 0x0000000004D5A1F8>

The whole query would be: `'INSERT INTO "characters_skillability" ("skill") VALUES (('Academics', 'Mental'))'` which is not valid.

It should be: `'INSERT INTO "characters_skillability" ("skill") VALUES (?,?)'` and unpack the tuple.

Is this possible?

**Comment by akx** [comment]
Tuples can't be stored in a single SQL column, that's right.
This looks like something you'd want to use a normal Django `ForeignKey` for.

```python
class Skill(models.Model):
  type = models.CharField(...)  # this could be an Enum, though! :)
  name = models.CharField(...)

class SomethingWithASkill(models.Model):
  skill = models.ForeignKey(Skill)
  # etc.
```

**Comment by AncientSwordRage** [comment]
I'd probably go for two enums, as both 'name' and 'type' have finite fixed lists of possible values.

I was hoping to be able to store information this was as pairing 'Academics - Physical' doesn't make sense. But I'll find a different way to work around this, possibly with validation.

**Comment by akx** [comment]
> as pairing 'Academics - Physical' doesn't make sense

You just made powerful enemies out of gym teachers.

**Comment by AncientSwordRage** [comment]
@akx Don't blame me, thats in the nWoD rulebook. :stuck_out_tongue_winking_eye:
