### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by David-OConnor** [hzdg/django-enumfields#36]
File "/home/david/anaconda3/lib/python3.4/site-packages/enumfields/fields.py", line 20, in __init__
    options["choices"] = [(i, getattr(i, 'label', i.name)) for i in self.enum]  # choices for the TypedChoiceField
TypeError: 'type' object is not iterable

**Comment by matthewwithanm** [comment]
Can you share a failing test please?

**Comment by David-OConnor** [comment]
from enum import Enum

from django.db import models
from enumfields import EnumIntegerField

class University(models.Model):
    class Control(Enum):
        public = 1
        private_nonprofit = 2
        private_forprofit = 3

    control = EnumIntegerField(Control)

I receive the TypeError when migrating.

**Comment by matthewwithanm** [comment]
Cool. Thanks for the update!

**Comment by macolo** [comment]
Note for people coming here from Google:

You need to inherit your enums from `Enum` not from `EnumField`
