### ISSUE TITLE
Django admin AttributeError 'unicode' object has no attribute 'value'

### ISSUE THREAD

**Issue by jessamynsmith** [hzdg/django-enumfields#41]
AttributeError at /admin/someapp/someclass/
'unicode' object has no attribute 'value'
Request Method:	GET
Request URL:	http://127.0.0.1:8000/admin/someapp/someclass/?continent2__exact=Continent.AFRICA
Django Version:	1.8.4
Exception Type:	AttributeError
Exception Value:	
'unicode' object has no attribute 'value'
Exception Location:	/Users/jessamyn/.virtualenvs/mentor/lib/python2.7/site-packages/enumfields/fields.py in get_prep_value, line 35

**Comment by lsowen** [comment]
:+1:

**Comment by ningsuhen** [comment]
+1.  Admin Filters by enum values don't work because of this.

**Comment by Amareis** [comment]
OMG, this affect and django-filters in rest-framework.
https://github.com/hzdg/django-enumfields/pull/46/commits/ed7d1d99437715055e327b243258225dc71154ca
This PR solve that problem, but it needs to be merged.

**Comment by akx** [comment]
Please use `EnumFieldListFilter` from #56 (will be in a released version soon) in the admin.

@Amareis: can you open a separate bug about any trouble you're having with Django REST Framework and django-filters regarding this?

**Comment by Amareis** [comment]
@akx don't think so, it was really long ago :)
I'm just copied enumfields in project and has applied [this](https://github.com/hzdg/django-enumfields/pull/46/commits/ed7d1d99437715055e327b243258225dc71154ca#diff-0d0002b8d572eae99755278bc4aeb328L35) change.
