### ISSUE TITLE
RemovedInDjango110Warning: SubfieldBase has been deprecated.

### ISSUE THREAD

**Issue by richarddewit** [hzdg/django-enumfields#45]
> /home/user/.virtualenvs/project/local/lib/python2.7/site-packages/enumfields/fields.py:92: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  class EnumField(EnumFieldMixin, models.CharField):

> /home/user/.virtualenvs/project/local/lib/python2.7/site-packages/enumfields/fields.py:92: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  class EnumField(EnumFieldMixin, models.CharField):

**Comment by johnthagen** [comment]
@akx Thanks for picking up maintenance on this!  Now that this and other issues are resolved, could we get a new release on PyPI?
