### ISSUE TITLE
Release new version (0.8?) on PyPI

### ISSUE THREAD

**Issue by johnthagen** [hzdg/django-enumfields#55]
A lot of recent fixes have been merged into the project now that @akx has graciously stepped up as a maintainer of the project (#44, #45, #53, #54, etc).  It would be great to get a new release on PyPI (version 0.8?) to make it easier to start using in production projects.

**Comment by akx** [comment]
@johnthagen I'll get around to doing that this week, hopefully! I still want to get a rebased #49 in that release.

**Comment by johnthagen** [comment]
@akx sounds great, thanks!

**Comment by akx** [comment]
Done! 🎉 

👉  https://pypi.python.org/pypi/django-enumfields/0.8.0 👈
