### ISSUE TITLE
Django migrations can't find enum classes nested in models

### ISSUE THREAD

**Issue by Pikkupomo** [hzdg/django-enumfields#57]
README describes that enums should be declared inside the class they are used in. 
```python
class MyModel(models.Model):

    class Color(Enum):
        RED = 'r'
        GREEN = 'g'
        BLUE = 'b'

    color = EnumField(Color, max_length=1)
```

This causes problems with Django because migrations cannot import the missing `Color` class. 

I think the proper example given should be something in the lines of: 
```python
class Color(Enum):
    RED = 'r'
    GREEN = 'g'
    BLUE = 'b'

class MyModel(models.Model):
    color = EnumField(Color, max_length=1)
```

**Comment by akx** [comment]
Thanks for the report (at last ;-) )

I'll see if I can do something about nested classes becoming recognizable by migrations (`__qualname__` might be the ticket -- we'll see); if not, I'll change the readme (and test cases) to not point people to do this.

**Comment by akx** [comment]
Oh and @Pikkupomo, which Django/Python environment is this in?

**Comment by akx** [comment]
Okay, so [the Django docs actually do mention](https://docs.djangoproject.com/en/1.9/topics/migrations/#serializing-values) that nested classes can't be serialized.

The `MyModel.Color` enum from the `tests` package gets serialized wrongly to

```python
('color', enumfields.fields.EnumField(enum=tests.models.Color, max_length=1)),
```

Of course you could manually edit the `enum` field there, but that might be tedious.

On Python 3, one could use `__qualname__` to construct a better qualified path to the object:

```python
>>> MyModel.Color
<enum 'Color'>
>>> MyModel.Color.__qualname__
'MyModel.Color'
>>> MyModel.Color.__name__
'Color'
>>>
```

but that's something Django would have to do, not this package. So changing the tests and docs!
