### ISSUE TITLE
Enum conversion inconsistencies

### ISSUE THREAD

**Issue by andrewdodd** [hzdg/django-enumfields#60]
When upgrading from 0.7.4 to 0.8.0 I found that the behaviour of enum fields has changed if you are initialising them via their String value rather than by their enum type.

This behaviour was a side effect of the changes to remove the deprecated SubfieldBase (826005087541805620be3daffab3e8d106eedc2f). 

I have had a short attempt at fixing this but haven't managed to find a way. (I'm thinking from my reading of the SubfieldBase related material that it might have something to do with replacing the `__new__` method).

I have written a test to demonstrate the issue:
```
# -- encoding: UTF-8 --

import pytest

from .models import MyModel

try:
    from .enums import Color # Use the new location of Color enum
except ImportError:
    Color = MyModel.Color    # Attempt the 0.7.4 location of color enum

@pytest.mark.django_db
def test_fields_value_is_enum_when_unsaved():
    obj = MyModel(color='r')
    assert Color.RED == obj.color

@pytest.mark.django_db
def test_fields_value_is_enum_when_saved():
    obj = MyModel(color='r')
    obj.save()
    assert Color.RED == obj.color

@pytest.mark.django_db
def test_fields_value_is_enum_when_created():
    obj = MyModel.objects.create(color='r')
    assert Color.RED == obj.color

@pytest.mark.django_db
def test_fields_value_is_enum_when_retrieved():
    MyModel.objects.create(color='r')
    obj = MyModel.objects.first()
    assert Color.RED == obj.color

```

To see the failure copy this test into a file in the `tests` directory and run

    > python manage.py test

To see it pass, checkout 0.7.4 and run it again!

**Comment by akx** [comment]
Thanks for the bug report!

Sure enough, that violates the Principle of Least Astonishment, and is a change in behavior from 0.7.x.

I dug in a little, and created this Django ticket about this: https://code.djangoproject.com/ticket/26807

**Comment by akx** [comment]
@andrewdodd: This is fixed in 0.8.1.

**Comment by andrewdodd** [comment]
Holy moly that was quick!

I dug a little into this on the weekend and came up with the same idea... that one would have to re-implement the SubfieldBase/Creator code, which felt bad.

Thanks!

**Comment by akx** [comment]
@andrewdodd Yeah, it felt strange, but looks like that's the way to go nevertheless -- and at the very least it fixes things for the time being.
