### ISSUE TITLE
ChoiceField.valid_value() Fails due to Label when filter with query params

### ISSUE THREAD

**Issue by legshort** [hzdg/django-enumfields#62]
I would like to report a weird action when I try to use filtering with DRF 3.4, django-filter 0.13 and django-enumfields 0.8.1, drf-enum-field 0.9.1
I made a request with url http://url/api/MyModels?test_type=a and the response said "['Select a valid choice. A is not one of the available choices.']".  
It turns out that ChoiceField.valid_value() returns False because [k, v in choices](https://github.com/django/django/blob/master/django/forms/fields.py#L819) are both label instead of name and value so it keeps failing.  
They should be name and value and tries to compare with query param which is 'a'.  
This is my sample code

``` pytyon
class TestType(Enum) 
    A = 'a'

    class Labels:
        A = 'a-label'

class MyModel(Model):
    test_type = EnumField(TestType, max_length=MAX_TEST_TYPE_LENGTH)
```

I think EnumField should override valid_value() and makes sure overridden method called instead of ChoiceField.

**Comment by akx** [comment]
Django-Enumfields 0.1.0? That's a positively _ancient_ version.

Can you try upgrading to a newer version?

Also, for interoperability with DRF, maybe see [this issue comment](https://github.com/hzdg/django-enumfields/issues/30#issuecomment-193017612) :)

**Comment by legshort** [comment]
my bad, I changed the version to django-enumfields 0.8.1 and drf-enum-field 0.9.1.
Yeah sure, let me try that, thanks.

**Comment by akx** [comment]
@legshort Any luck?

**Comment by akx** [comment]
Closing as ancient.
