### ISSUE TITLE
Provide example (or support?) for using an EnumField directly in a form

### ISSUE THREAD

**Issue by johnthagen** [hzdg/django-enumfields#64]
Django provides [Form fields](https://docs.djangoproject.com/en/1.9/ref/forms/fields/) that can be used directly in `Form` objects.

Does `django-enumfields` provide an `EnumField` that can be used directly in a form like:

```
from django import forms
import enumfields

class MyForm(forms.Form):
    my_enum = enumfields.  # ... ?
```

I can get it to work if I put an `enumfields.EnumIntegerField` into a `Model` and then use a `ModelForm`, but if I just want to create a `Form` without a `Model` I couldn't figure out how to do this.

I'm happy to submit a PR with an example if someone could teach me how to do this. :)

**Comment by akx** [comment]
`enumfields.EnumField(MyEnum).formfield()` should work. :)

**Comment by johnthagen** [comment]
@akx Thanks!  If I submitted a PR with a small example on how to use `enumfields` directly in a `Form`, would you accept?  I think this is something that could help others in the future.

**Comment by akx** [comment]
Of course! There's no such thing as too much documentation!

(Provided the documentation is correct -- documentation-wise, can't think of a worse thing than docs that outright lie, but that usually happens due to rot, so not the point here. :-) )
