### ISSUE TITLE
Django admin filter is broken for enum fields

### ISSUE THREAD

**Issue by jansegre** [hzdg/django-enumfields#75]
The url that django generates for filers (`field__exact=x`) ends up using `str(some_enum)` instead of `some_enum.value`  for `x`.

This is can be tested by adding a `field_x` (which is an enum field) to the `filters = ('field_x',)` of a registered model admin.

**Comment by jacebrowning** [comment]
The README says to use:

```python
from enumfields.admin import EnumFieldListFilter

class MyModelAdmin(admin.ModelAdmin):
  list_filter = [('color', EnumFieldListFilter)]
```

**Comment by jansegre** [comment]
Thanks! This is what I was looking for. I don't know how I missed it.

If there is normal any way to make this automatic I'd be glad to help.
