### ISSUE TITLE
Cannot save a model when setting an enum value

### ISSUE THREAD

**Issue by jbowmanp1107** [hzdg/django-enumfields#76]
I am receiving an error when I try to save a model object when I set an enum:

Error binding parameter 3 - probably unsupported type.

My dev DB is sqlite.

model simply contains an my_enum_field = EnumIntegerField(enum=MyEnumType)

view is simply trying to set the value of this enum field:

my_model.my_enum_field = MyEnumType.MYVALUE
my_model.save()

Any idea why this might be happening? 

The completely strange thing is, I am using django rest framework and this isn't the first time I've used EnumIntegerField, in that other case, the value is being saved from the serializer and never directly from the view.

Edit: After more research it seems that, the value is trying to be saved to the database as a tuple. Also when an integer is manually saved into the database, I am getting validation errors when trying to read the value (e.g. 0 is not a valid enum value errors)

**Comment by Gpzim98** [comment]
Same problem here

django-enumfield==1.3b2
Django==1.11.2

**Comment by akx** [comment]
Closing as an ancient issue (and our tests indicate this _should_ work).

If this still persists, please open a new issue with a suitable repro case. Thank you!
