### ISSUE TITLE
Breaks with django 2.0 

### ISSUE THREAD

**Issue by codetutoraj** [hzdg/django-enumfields#82]
New Django breaks this package. Particularly, when we serialize a query to JSON.

Field._get_val_from_obj() will be removed in favor of Field.value_from_object().
https://docs.djangoproject.com/en/dev/internals/deprecation/#deprecation-removed-in-2-0

It's being used here in line 81

value = self._get_val_from_obj(obj)
https://github.com/hzdg/django-enumfields/blob/master/enumfields/fields.py

**Comment by si14** [comment]
There is a PR for that already: https://github.com/hzdg/django-enumfields/pull/83 Hope it will be merged!

**Comment by si14** [comment]
An update for anyone interested: the project now seems to be compatible with Django 2.0.

**Comment by johnthagen** [comment]
#83 has been merged. Is this issue resolved?
