### ISSUE TITLE
Calculate max_length automatically?

### ISSUE THREAD

**Issue by ADR-007** [hzdg/django-enumfields#86]
Hi all,

I think it will be nice when the max_length will be calculated automatically by default.

What do you think?

**Comment by akx** [comment]
I don't know. [The Zen of Python](https://www.python.org/dev/peps/pep-0020/) says

> Explicit is better than implicit.

after all.

Having a dynamic `max_length` would cause spurious, surprising migrations to occur if the enum changes.

Validating the given `max_length` to make sure it can accommodate all of the values for the given enum would be a good idea though.

**Comment by ADR-007** [comment]
I added `auth_length` argument in [PR](https://github.com/hzdg/django-enumfields/pull/91).
