### ISSUE TITLE
Support Field attributes (like 'name', etc)

### ISSUE THREAD

**Issue by DarkThor76** [hzdg/django-enumfields#88]
I'm using Django 2.1 and I get errors when I attempt to put a name on an EnumField like:

```
from django.utils.translation import ugettext_lazy as _
from enumfields import EnumField, Enum


class Grade(Enum):
    FRESHMAN = 'fr'
    SOPHOMORE = 'sp'
    JUNIOR = 'jr'
    SENIOR = 'sr'


grade = EnumField(name=_('grade'), enum=Grade, max_length=2)
```

When I attempt to make migrations the error is TypeError: getattr(): attribute name must be string

**Comment by akx** [comment]
You'll want `verbose_name=_('grade')` there. This is not really related to `django-enumfields`.
