### ISSUE TITLE
Is the project alive?

### ISSUE THREAD

**Issue by ADR-007** [hzdg/django-enumfields#96]
Hi!

I did several pull requests two months ago, but they aren't approved or rejected yet.

Currently, I have several new improvements ideas. Should I make a pull request or it will never be approved?

**Comment by barseghyanartur** [comment]
Maintainers:

Please, respond.

**Comment by johnthagen** [comment]
Pinging @akx @hzdg @matthewwithanm

**Comment by matthewwithanm** [comment]
Sorry, I'm not one of the maintainers anymore. @talebbits, @akx and @lettertwo would know better.

**Comment by ADR-007** [comment]
@aamorozov , @elainen , @gew and @ryanbagwell maybe you have permissions to merge PRs and deploy a new version of the library?

I need Django 3 support :(

**Comment by barseghyanartur** [comment]
@ADR-007:

Why don't you re-brand your fork? I mean, if you plan to provide a better maintenance, sometimes it's the best way. My personal experience (did that a couple of times), give a full credit to authors, mention that it's a drop-in replacement, add ``-reloaded`` suffix (for example, ``django-enumfields-reloaded``), register a PyPI package, upload, keep CHANGELOG up-to-date and be ready to submit another PR to the main package if package author asks for it after a year or so.

**Comment by akx** [comment]
I tried contacting @hzdg and @talebbits a while back (we at @valohai would be happy to take over maintenance), but no official response re transferring yet.

**Comment by talebbits** [comment]
ok we added @akx as collaborator.

**Comment by johnthagen** [comment]
Thanks @talebbits! Does this mean he can also upload new releases to PyPI?

**Comment by barseghyanartur** [comment]
@johnthagen:

Check this: https://pypi.org/project/django-enumfields/

I see @akx in the list of maintainers and ``django-enumfields`` in the list of packages he maintains.

**Comment by akx** [comment]
@talebbits Thank you! But can you also give me write (and/or admin) rights on this repository?

**Comment by akx** [comment]
Closing since we're back in action!

**Comment by larsrinn** [comment]
Awesome to see some action here!
